services:
  - type: web
    name: streamlit-polars-app
    env: python
    plan: free
    region: oregon

  
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
    
    rootDir: ./
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6